### PR TITLE
Bug-fix: close modal loadingIndicator enabled

### LINKED ISSUE #3064: Bug on closeModal
Given Setup:
```
                {
                pathSegment: 'mf',
                label: 'mf',
                //  loadingIndicator: { enabled: false },
                viewUrl: '/microfrontend.html',
              },
              {
                category: 'MFs',
                pathSegment: 'mf2',
                label: 'mf2',
                loadingIndicator: { enabled: false },
                viewUrl: '/microfrontend2.html',
              },
```
If `mf` is opened as modal and `Luigi.reset()` is called a user cannot close the modal via [x] button. Closing the modal with `mf2` is working.
Difference: `loadingIndicator`

### PR DESCRIPTION
**Pull request by JohannesDoberer**
Fixes #3064

### CODE REVIEW

File: core/src/Modal.svelte [hunk 1]
```diff
@@ -233,12 +234,13 @@
     }
 
     if ('luigi.get-context' === e.data.msg) {
+      contextRequested=true;
```
Comment (ndricimrr) [inline core/src/Modal.svelte:237]:
```suggestion
      contextRequested = true;
```

File: core/src/Modal.svelte [hunk 2]
```diff
@@ -281,6 +283,11 @@
         )
       : '';
     window.focus();
+    setTimeout(()=>{
+      if(!contextRequested){
+        showLoadingIndicator=true;
+      }
+    },250);
```
Comment (ndricimrr) [inline core/src/Modal.svelte:290]:
```suggestion
    setTimeout(() => {
      if(!contextRequested){
        showLoadingIndicator = true;
      }
    }, 250);
```

File: core/src/Modal.svelte [hunk 3]
```diff
@@ -300,6 +307,16 @@
       dispatch('close');
     }
   }
+
+  function fadeOutLoadingIndicator() {
```
Comment (ndricimrr) [inline core/src/Modal.svelte:311]: Could we add a JSDoc to it maybe

File: core/src/Modal.svelte [hunk 4]
```diff
@@ -300,6 +307,16 @@
...
+    const spinnerContainer = document.querySelector('.spinnerContainer');
+    if (spinnerContainer && spinnerContainer.classList.contains("fade-in-out")) {
+      spinnerContainer.classList.remove("fade-in-out");
+      setTimeout(function() {
+        showLoadingIndicator = false;
+      },250);
```
Comment (ndricimrr) [inline core/src/Modal.svelte:317]:
```suggestion
      }, 250);
```

**Review by ndricimrr — COMMENTED** [review]
Some initial small comments

File: core/src/Modal.svelte [hunk 5]
```diff
@@ -300,6 +307,21 @@
       dispatch('close');
     }
   }
+
+  /**
+   * This function will be called if the context the LuigiClient requests the context.
```
Comment (ndricimrr) [inline core/src/Modal.svelte:312]: I think there is a typo here as I can't understand properly.

File: core/src/Modal.svelte [hunk 6]
```diff
@@ -281,6 +283,11 @@
         )
       : '';
     window.focus();
+    setTimeout(() => {
```
Comment (ndricimrr) [inline core/src/Modal.svelte:286]: could you comment to this. Just an inline comment would be enough but also very helpful to understand

**Review by ndricimrr — COMMENTED** [review]
Some more small comments. Tested it out worked as expected

**Review by ndricimrr — APPROVED** [review]
