### PR TITLE
Error handling on productswitcher columns calculation

### LINKED ISSUE #2650: Investigate daily dashboard console error
**Description**
- There seems to be an error showing on our Dashboard:
Screenshot 2022-04-07 at 13 56 05

Right when loading the page

**Expected result**
no errors should show, or uncaught exception be handled. Investigate root of the issue and issue fix as needed.

### PR DESCRIPTION
**Pull request by JohannesDoberer**
Fixes #2650

### CODE REVIEW

File: core/src/utilities/helpers/navigation-helpers.js [hunk 1]
```diff
@@ -19,8 +19,14 @@ class NavigationHelpersClass {
 
   getProductSwitcherColumnsNumber() {
     const productSwitcherConfig = this.getProductSwitcherConfig();
+    if (!productSwitcherConfig.items) return;
```
Comment (wdoberschuetz) [inline core/src/utilities/helpers/navigation-helpers.js:22]: (n2h) Could we get a test case where items ```undefined``` or ```null```? :)

File: core/src/utilities/helpers/navigation-helpers.js [hunk 2]
```diff
@@ -19,8 +19,14 @@ class NavigationHelpersClass {
...
     let productSwitcherColumns = productSwitcherConfig.columns;
```
Comment (wdoberschuetz) [inline core/src/utilities/helpers/navigation-helpers.js:23]: (n2h) This seems to be never reassigned so it could be a const.

**Review by wdoberschuetz — APPROVED** [review]
