### PR TITLE
Debug cypress travis issue

### LINKED ISSUE #1085: Investigate pipeline issues in travis
Issue opened at travis community. https://travis-ci.community/t/cypress-chrome-all-build-broken-at-same-time/7166
It looks like Chrome 80 is the issue.

### PR DESCRIPTION
**Pull request by maxmarkus**
Fixes #1085 by installing the fixed chromium-browser version 79 in travis.

### CODE REVIEW

File: core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js [hunk 1]
```diff
@@ -234,8 +234,6 @@ class Navigation {
     defaultLabel: 'Select Environment ...',
     parentNodePath: '/environments', // absolute path
     lazyloadOptions: true, // load options on click instead on page load
-    preserveSubPathOnSwitch: true,
```
Comment (marynaKhromova) [inline core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js]: maybe these changes are not relevant to this PR. the same for `core/src/navigation/services/navigation.js`
