### PR TITLE
Fix go back context multiple modals

### LINKED ISSUE #3391: goback value not passed  in nested modal scenario

### PR DESCRIPTION
**Pull request by ndricimrr**
**Description**

GoBack api was sending context back to main Iframe instead of the previous modal iFrame in the case of multiple modals.

Changes proposed in this pull request:

- handle case when multiple modals are open by grabbing the previous modal and sending the context back to it instead

**Related issue(s)**

Fixes #3391

### CODE REVIEW

File: core/src/App.svelte [hunk 1]
```diff
@@ -1577,9 +1578,19 @@
...
+          let modalConfig = config;
+          // special case if going back with multiple modals, context should go back to previous modal, not main iframe
+          if (mfModalPreviousElement && mfModalPreviousElement.modalIframeData && mfModalPreviousElement.modalIframe){
+            const topMostModal = mfModalPreviousElement;
+            const topMostModalData = topMostModal.modalIframeData;
+            modalConfig = Object.assign({}, {
+               pathParams: topMostModalData.pathParams,
+               context: topMostModalData.context,
+               iframe: topMostModal.modalIframe
+            });
```
Comment (ndricimrr) [inline core/src/App.svelte:1590]:
```suggestion
            modalConfig =  {
               pathParams: topMostModalData.pathParams,
               context: topMostModalData.context,
               iframe: topMostModal.modalIframe
            };
```

**Review by JohannesDoberer — APPROVED** [review]
